created bookService online-book-store
OlgaStarikova/online-book-store pull request #1
Opened 2024-02-24 18:13 UTC by OlgaStarikova

2024-02-25 12:54 UTC, okuzan requested changes

2024-02-25 12:54 UTC, okuzan commented on pom.xml
> +        <java.version>20</java.version>
why java 20? it's not LTS (long time support) release, I'd suggest switching to either 17 or 21 (preferably 17, it's in task descirption)

2024-02-25 12:54 UTC, okuzan commented on src/main/resources/application.properties
> +
```suggestion
```

2024-02-25 18:56 UTC, okuzan approved these changes

2024-03-02 11:24 UTC, olekskov requested changes

2024-03-02 11:24 UTC, olekskov commented on src/main/java/com/example/onlinebookstore/dto/BookDto.java
> +    private Long id;
It's not an entity, please remove annotations
```suggestion
public class BookDto {
    private Long id;
```

2024-03-02 11:24 UTC, olekskov commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
same
```suggestion
```

2024-03-02 11:24 UTC, olekskov commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
> +    private Long id;
Id is assigned by DB, when you send request to create something you should not pass Id. User will obtain Id in response after creation
```suggestion
```

2024-03-02 11:24 UTC, olekskov commented on src/main/java/com/example/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +        }
please add catch block

2024-03-03 19:03 UTC, okuzan requested changes

2024-03-03 19:03 UTC, okuzan commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    private BigDecimal price;
these are critical fields, they shouldn't be nullable

2024-03-07 22:27 UTC, merged