Shopping Cart service
OlgaStarikova/online-book-store pull request #12
Opened 2024-06-07 08:33 UTC by OlgaStarikova

2024-06-07 11:24 UTC, Elena-Bruyako requested changes
Let's fix some comments

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +@Table(name = "cartitems")
```suggestion
@Table(name = "cart_items")
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +@Table(name = "shoppingcarts")
```suggestion
@Table(name = "shopping_carts")
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/CartService.java
> +
```suggestion
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/CartServiceImpl.java
> +    public CartItemDto save(String email, CreateCartItemRequestDto requestDto) {
```suggestion
    public ShoppingCartDto save(String email, CreateCartItemRequestDto requestDto) {
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/CartServiceImpl.java
> +        CartItem cartItem = cartMapper.toCartItemModel(requestDto);
let's make your code more readable
Create Book book = repo.find
ShoppingCart cart = repo.find
cart.getCartItems() -> add new cartItem, check if there is already bookId exists then increase quantity
if no -> add new cartItem

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/UserServiceImpl.java
> +        ShoppingCart cart = new ShoppingCart();
It's better to create method createShoppingCart(User user) in ShopCartService and call it here

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/CartServiceImpl.java
> +    public CartItemDto update(Long id, UpdateCartItemRequestDto requestDto) {
```suggestion
    public ShoppingCartDto update(Long id, UpdateCartItemRequestDto requestDto) {
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/10-create-shoppingcart-table.yml
> +            tableName: shoppingcarts
Check comments in Entity

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/11-create-cartitem-table.yml
> +      id: create-cartitems-table
```suggestion
      id: create-cart-items-table
```

2024-06-07 11:24 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/11-create-cartitem-table.yml
> +                    foreignKeyName: fk_cartitems_shoppingcarts
```suggestion
                    foreignKeyName: fk_cart_items_shoppingcarts
```
Check all places

2024-06-08 05:45 UTC, Elena-Bruyako requested changes
leave comments

2024-06-08 05:45 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/CreateCartItemRequestDto.java
> +        @Min(1)
```suggestion
        @Positive
```

2024-06-08 05:45 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/UpdateCartItemRequestDto.java
> +        @Min(1)
```suggestion
        @Positive
```

2024-06-08 05:45 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/mapper/ShoppingCartMapper.java
> +    CartItemDto toCartItemDto(CartItem cartItem);
It's better to create CartItemMapper to separate logic from ShoppingCartMapper

2024-06-08 05:45 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/CartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(id)
```suggestion
        ShoppingCart cart = repository.findByUserId(userId);
        CartItem cartItem = itemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())
                .map(item -> {
                    item.setQuantity(itemDto.quantity());
                    return item;
                }).orElseThrow(() -> new EntityNotFoundException(
                        String.format("No cart item with id: %d for user: %d", cartItemId, userId)
                ));
        itemRepository.save(cartItem);
        return cartMapper.toDto(cart);
```

2024-06-08 05:45 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/CartServiceImpl.java
> +    public ShoppingCart createShoppingCart(ShoppingCart shoppingCart) {
```suggestion
    public void createShoppingCart(User user) {
        ShoppingCart shoppingCart = new ShoppingCart();
        shoppingCart.setUser(user);
        repository.save(shoppingCart);
    }
```

2024-06-08 05:45 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/UserServiceImpl.java
> +        ShoppingCart cart = new ShoppingCart();
```suggestion
        cartService.createShoppingCart(user);
```

2024-06-08 13:25 UTC, okuzan requested changes

2024-06-08 13:25 UTC, okuzan commented on src/main/java/com/example/onlinebookstore/controller/ShoppingCartController.java
> +    public ShoppingCartDto getShoppingCart() {
add @ Operation here too

2024-06-08 13:25 UTC, okuzan commented on src/main/java/com/example/onlinebookstore/dto/CreateCartItemRequestDto.java
> +        Long bookId,
you can use @ Positive on long ids in request DTOs too

2024-06-08 13:25 UTC, okuzan commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +@SQLRestriction("is_deleted = false")
```suggestion
@SQLDelete(sql = "UPDATE cart_items SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction("is_deleted = FALSE")
```
they are SQL keywords too

2024-06-08 13:25 UTC, okuzan commented on src/main/java/com/example/onlinebookstore/service/impl/CartServiceImpl.java
> +    }
make this private
put it after all public methods

2024-06-08 13:25 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/11-create-cartitem-table.yml
add empty line

2024-06-08 13:25 UTC, okuzan commented on src/main/resources/db/changelog/changes/11-create-cartitem-table.yml
> +                    nullable: false
add empty line

2024-06-10 06:54 UTC, Elena-Bruyako approved these changes
Well done!

2024-06-24 19:49 UTC, merged