Validation and global exception handler were added
OlgaStarikova/online-book-store pull request #5
Opened 2024-03-22 20:09 UTC by OlgaStarikova

2024-03-23 09:47 UTC, olekskov requested changes

2024-03-23 09:47 UTC, olekskov commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
>      private BigDecimal price;
Please check also ```@NotEmpty, @NotBlank, @ISBN``` annotations and make more strict validations where appliable

2024-03-26 10:39 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
>      private String title;
```suggestion
    @NotBlank
    private String title;
```

2024-03-26 10:39 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
>      private String isbn;
```suggestion
    @Isbn
    private String isbn;
```

2024-03-27 10:10 UTC, Rommelua approved these changes

2024-03-29 20:54 UTC, merged