spring boot security, roles, PreAuthorize access
OlgaStarikova/online-book-store pull request #8
Opened 2024-05-13 13:40 UTC by OlgaStarikova

2024-05-13 16:52 UTC, kerrrusha requested changes

2024-05-13 16:52 UTC, kerrrusha commented on src/main/resources/db/changelog/changes/04-create-user-role-table.yml
> +                    uniqueConstraintName: user_id-role_id_unique
what about foreign keys?

2024-05-14 06:12 UTC, Elena-Bruyako requested changes
Let's improve your solution!

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/config/SecurityConfig.java
> +@EnableMethodSecurity
Do you need both annotation here `@EnableWebSecurity and @EnableMethodSecurity`

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
>      public BookDto updateBook(@PathVariable Long id, @RequestBody CreateBookRequestDto requestDto) {
```suggestion
    public BookDto updateBook(@PathVariable Long id, @RequestBody @Valid CreateBookRequestDto requestDto) {
```

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
>      public List<BookDto> search(BookSearchParameters searchParameters) {
```suggestion
    public List<BookDto> search(BookSearchParameters searchParameters, @ParameterObject @PageableDefault Pageable pageable) {
```

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
>      public List<BookDto> getAll(Pageable pageable) {
```suggestion
    public List<BookDto> getAll(@ParameterObject @PageableDefault Pageable pageable) {
```

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Role.java
> +@Entity
```suggestion
@Entity
@Data
```
or add necessary annotations

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/UserServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(requestDto.password()));
Do we need to set Role.USER here?

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/UserServiceImpl.java
> +        User user = new User();
```suggestion
        User user = userMapper.toUser(requestDto);
        user.setPassword(passwordEncoder.encode(requestDto.password()));
        user.setRoles(...
        return userMapper.toDto(userRepository.save(user));
```

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/04-create-user-role-table.yml
> +                  constraints:
```suggestion
                  constraints:
                    foreignKeyName: fk_users_roles_users
                    referencedTableName: users
                    referencedColumnNames:  id
                    nullable:  false
```

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/04-create-user-role-table.yml
> +                  constraints:
```suggestion
                  constraints:
                    foreignKeyName: fk_users_roles_roles
                    referencedTableName: roles
                    referencedColumnNames:  id
                    nullable:  false
```

2024-05-14 06:12 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/08-addFK-user-role-table.yml
> +  -  changeSet:
You actually don't need this changelog

2024-05-15 06:20 UTC, Elena-Bruyako approved these changes
Good job!

2024-05-20 21:06 UTC, merged